---
title: "Credit Score"
author: "Cheng Jun"
output: html_document
---
```{r}
library(caTools)
library(ggplot2)
library(randomForest)
library(caret) 
```


```{r}
setwd('C:/Users/Cheng Jun/repos3/rstudio/R-Programming')
data <- read.table("bank.csv",header=1,sep = ';')
sum(is.na(data))
columns = names(data)
head(data)
```

```{r}
#Illustration of Data 
#plot age row
ggplot(data) + geom_bar(aes(y = age))
#plot job row
ggplot(data) + geom_bar(aes(y = job))
#plot marital row
ggplot(data) + geom_bar(aes(y = marital))
#plot education row
ggplot(data) + geom_bar(aes(y = education))
#plot default row
ggplot(data) + geom_bar(aes(y = default))
#As default has mostly 'no' value if we place it in the dataframe it might result in overfitting due to it not being equally distributed.  
data = data[,-c(5)] 
#plot housing row
ggplot(data) + geom_bar(aes(y = housing))
#plot loan row
ggplot(data) + geom_bar(aes(y = loan))
#plot contact row
ggplot(data) + geom_bar(aes(y = contact))
#plot day row
ggplot(data) + geom_bar(aes(y =day))
#plot month row
ggplot(data) + geom_bar(aes(y = month))
#plot duration row
ggplot(data) + geom_bar(aes(y =duration))
#plot campaign row
ggplot(data) + geom_bar(aes(y =campaign))
#for pdays row
ggplot(data, aes(x = pdays)) + geom_histogram(fill="grey", position="dodge",binwidth=100)
data$pdays[data$pdays==-1] = mean(data$pdays)
#plot poutcome row
ggplot(data) + geom_bar(aes(y = poutcome))
#As poutcome also mostly has unknown only, so we remove it to prevent overfitting from occuring
data = data[,-c(15)]
#plot y row 
ggplot(data) + geom_bar(aes(y =y))

```



```{r}
#for balance row
data$balance[data$balance==0] = mean(data$balance)

data <- transform(
  data,
  age = age,
  job = as.integer(factor(job)),
  marital = as.integer(factor(marital)),
  education=as.integer(factor(education)),
  balance = balance,
  housing = as.integer(factor(housing)),
  loan = as.integer(factor(loan)),
  contact = as.integer(factor(contact)),
  day = day,
  month = as.integer(factor(month)),
  duration = duration,
  campaign = campaign,
  pdays = pdays
)
sapply(data, class)

#train test split
split = sample.split(data$y,SplitRatio=0.7)
training = subset(data,split==TRUE)
test = subset(data,split==FALSE)

#scaling the data
training[,c(1:14)] = scale(training[,c(1:14)])

#random forest
rf <- randomForest(
  as.factor(y) ~ .,
  data=training,
)

test[,c(1:14)] = scale(test[,c(1:14)])

```


```{r}
pred = predict(rf, newdata=test[,c(1:14)])
cm = table(test[,15], pred)
#confusion matrix
fourfoldplot(cm, color = c("#CC6666", "#99AA99"),conf.level = 0, margin =1, main = "Confusion Matrix")

res = confusionMatrix(cm)

print(res)
Precisionvalue = res$byClass["Pos Pred Value"]
print(Precisionvalue)

Accuracy=res$overall["Accuracy"]
print(Accuracy)

```